In [2]:
import numpy as np
import tensorflow as tf

In [26]:
x = tf.Variable(tf.constant(1.0, shape=[1, 2]))
x2 = tf.Variable(tf.constant(2.0, shape=[1, 2]))
w = tf.Variable(tf.constant(1.0, shape=[2, 1]))
y = tf.reduce_sum(tf.matmul(x,w))

In [27]:
sess = tf.InteractiveSession()
sess.run(tf.initialize_all_variables())


In [5]:
print sess.run(y)

2.0


In [15]:
grad = tf.gradients(y,x)

In [10]:
print w.dtype

<dtype: 'float32_ref'>


In [18]:
print sess.run(grad)[0][0]

[ 1.  1.]


In [30]:
print x.eval()

[[ 1.  1.]]


In [31]:
update = x.assign_add(x2)

In [32]:
print x.eval()

[[ 1.  1.]]


In [33]:
sess.run(update)

array([[ 3.,  3.]], dtype=float32)

In [34]:
print x.eval()

[[ 3.  3.]]


In [35]:
print sess.run(grad)

[array([[ 1.,  1.]], dtype=float32)]


In [36]:
update2 = x.assign_add(grad[0])

In [41]:
print sess.run(update2)

[[ 8.  8.]]
